--2，在B部门中“李”姓员工的人数
SELECT COUNT() AS B部门中“李”姓员工的人数
FROM USERS
LEFT JOIN SECTION 
ON USERS.SECTIONCODE=SECTION.CODE
WHERE SECTIONCODE = 'B' AND NAME LIKE '李%'

--3，工资表中是否存在“王五”
SELECT *
FROM SALARY
WHERE EXISTS (SELECT SALARY.CODE
FROM SALARY
LEFT JOIN USERS
ON USERS.CODE = SALARY.CODE
WHERE NAME = '王五')

select case when SALARY=NULL then '有王五' else '无' END as '是否有王五'
from USERS
	FULL JOIN SALARY
	ON USERS.CODE = SALARY.CODE
WHERE NAME='王五'
--3.1工资表中是否存在“小明”，有则显示(EXISTS 内外表连接）
SELECT T.CODE, T1.NAME 
FROM SALARY T
	LEFT JOIN USERS T1 
	ON T.CODE=T1.CODE
WHERE EXISTS
	(SELECT 1 
	FROM SALARY T2 
	LEFT JOIN USERS T3 
	ON T2.CODE=T3.CODE 
	WHERE T3.NAME='小明' AND T.CODE=T2.CODE)

--4，对2022年9月工资进行排序，从大到小排序
SELECT YM AS '2022年9月', SALARY AS 工资
FROM SALARY
WHERE YM=202209 
ORDER BY SALARY DESC

--5，查询出“张三”和“李四”每个月的工资，显示月份和工资即可（使用IN语句、使用左连接方式关联表）
SELECT  NAME AS 姓名,YM AS 年月,SALARY AS 工资
    FROM SALARY
        LEFT JOIN USERS
        ON USERS.CODE=SALARY.CODE
WHERE NAME IN ('张三','李四')

--6，使用case when计算出男女的工资总和各是多少？
SELECT 
	SUM (CASE WHEN  USERS.SEX = 1 THEN SALARY ELSE 0 END) AS 男性工资总和,
	SUM (CASE WHEN  USERS.SEX = 0 THEN SALARY ELSE 0 END) AS 女性工资总和
FROM SALARY,USERS
WHERE USERS.CODE=SALARY.CODE

SELECT SEX AS '性别',SUM(SALARY) AS '工资总和'
FROM SALARY
    LEFT JOIN (SELECT CODE, CASE WHEN USERS.SEX = 1 THEN '男' ELSE '女' END AS SEX 
                FROM USERS)AS USERS1
    ON USERS1.CODE=SALARY.CODE
GROUP BY SEX

--找A部门和B部门中分别工资最高的前三
SELECT * 
FROM(
	SELECT  T1.CODE, T1.NAME, T1.SECTIONCODE, T.SALARY, T.YM, ROW_NUMBER()OVER(PARTITION BY T1.SECTIONCODE ORDER BY T.SALARY DESC)ROW_NUM
	FROM SALARY T
	LEFT JOIN USERS T1 ON T.CODE = T1.CODE )T2
WHERE T2.ROW_NUM <=3;